### ISSUE TITLE
Fix price on index.html when locally stored price does not exist

### ISSUE THREAD

**Issue by ThoernVE** [CanNotBan/CanInteBan#83]

**Comment by Pandangeloo** [comment]
It works for me most of the times.

**Comment by ThoernVE** [comment]
> It works for me most of the times.

It works if you have a locally stored price. Says NaN when we dont have a price to start with./
Can be tested by deleting the local storage

**Comment by ThoernVE** [comment]
Possibly only malfunctions on FireFox?
